name: Generar Reporte R y Notificar

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'   # Todos los días a las 5 AM UTC
  workflow_dispatch:

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    env:
      REDCAP_API_KEY: ${{ secrets.REDCAP_API_KEY }}
      TOKEN_PAT: ${{ secrets.TOKEN_PAT }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias de R (con sistema)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            sf
            leaflet
            viridis
            lubridate
            rmarkdown
            remotes

      - name: Instalar redcapAPI desde GitHub
        run: |
          Rscript -e "remotes::install_github('nutterb/redcapAPI')"

      - name: Renderizar el Rmd
        run: |
          Rscript -e "rmarkdown::render('00_data_validation.Rmd')"

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-html
          path: reporte.html

      - name: Notificar a Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"✅ Reporte generado automáticamente el día $(date -u +'%Y-%m-%d %H:%M UTC') para el repo \`${{ github.repository }}\`.\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
