name: Generar Reporte R y Notificar

on:
  schedule:
    - cron: '0 5 * * *'   # Todos los días a las 5 AM UTC

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    env:
      REDCAP_API_KEY: ${{ secrets.REDCAP_API_KEY }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar paquetes necesarios
        run: |
          Rscript -e "install.packages(c('tidyverse', 'sf', 'leaflet', 'viridis', 'lubridate', 'rmarkdown'), repos = 'https://cloud.r-project.org')"
          Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes')"
          Rscript -e "remotes::install_github('nutterb/redcapAPI')"

      - name: Renderizar el Rmd
        run: |
          Rscript -e "rmarkdown::render('00_data_validation.Rmd')"

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: reporte-html
          path: reporte.html

      - name: Notificar a Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"✅ Reporte generado automáticamente el día $(date -u +'%Y-%m-%d %H:%M UTC') para el repo \`${{ github.repository }}\`.\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
