name: Generar Reporte R y Notificar

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'   # Todos los días a las 5 AM UTC
  workflow_dispatch:

jobs:
  render-rmd:
    runs-on: ubuntu-latest

    env:
      REDCAP_API_KEY: ${{ secrets.REDCAP_API_KEY }}
      TOKEN_PAT: ${{ secrets.TOKEN_PAT }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias del sistema requeridas para sodium, keyring y redcapAPI
        run: |
          sudo apt-get update
          sudo apt-get install -y libgit2-dev libssl-dev libssh2-1-dev libsodium-dev

      - name: Instalar dependencias de R (con sistema)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            sf
            leaflet
            viridis
            lubridate
            rmarkdown
            remotes

      - name: Instalar redcapAPI desde GitHub
        run: |
          export GITHUB_PAT=${TOKEN_PAT}
          Rscript -e "remotes::install_github('nutterb/redcapAPI')"
        env:
          TOKEN_PAT: ${{ secrets.TOKEN_PAT }}

      - name: Renderizar el Rmd
        run: |
          Rscript -e "rmarkdown::render('00_data_validation.Rmd', output_file = 'index.html')"

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-html
          path: index.html
          if-no-files-found: error

      - name: Notificar a Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"✅ Reporte generado automáticamente el día $(date -u +'%Y-%m-%d %H:%M UTC') para el repo \`${{ github.repository }}\`.\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"✅ Reporte generado automáticamente el día $(date -u +'%Y-%m-%d %H:%M UTC'). Puedes verlo aquí 👉 https://healthinnovation.github.io/hmz-censo/ \nRepositorio: \`${{ github.repository }}\`\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL_2 }}

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
